FROM cr.msk.sbercloud.ru/aicloud-jupyter/jupyter-cuda11.1-pt1.8.1-gpu-a100

COPY requirements.txt .
COPY install_sc2.sh .

# Install Dependencies
RUN pip install -r requirements.txt \
&& pip install torch==0.4.1.post2 -f https://download.pytorch.org/whl/torch_stable.html

# Install StarCraft2 and Maps
RUN bash install_sc2.sh
